### ISSUE TITLE
Suspension position

### ISSUE THREAD

**Issue by Sekkmer** [Project-Pandora-Game/pandora#105]
by default, it doesn't require a new image to be added to a layer just turns the character 180° upside down

allow assets to have new images in this pose, like hair, skirt, chain, and so on

this pose shouldn't be accessible from the pose menu and can only be achieved by an item like a suspension rope

**Comment by Jomshir98** [comment]
Few more things to consider:
- Other angles than 180 might be useful; e.g. 90/270 for laying down
- What is the "anchor" point around which the rotation happens? I think best would be using the existing anchor point shown in yellow when using debug overview
- Some Y offset from normal ground position might be required if the rotation point is not on geometric median to avoid character seemingly going under the floor
- It might be useful to allow specifying this manually, too - we are a roleplay platform and users should be able to achieve some things we don't support even without having to resort to "items that are actually not there" just to have the effect they want
