### ISSUE TITLE
Make room background filtering work

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#165]
The filter in the room background selector currently do not work.

The room background definition file in the asset repo has potential tags for each room added as a comment.

The goal is to convert them into tags that can be read, collected and populated in the room background selector popup or potentially also in the room list search/filtering later on.

**Comment by Jomshir98** [comment]
Note: The tags already are in machine-readable format (done in #195). Only thing left is implementing search and tag filtering on client.
Optimal solution would be allowing filtering of multiple tags at the same time but simple "select" should be helpful enough for first iteration.
