### ISSUE TITLE
Fix pose sliders of the client that can get stuck

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#272]
Bug:
If you open the Pose tab on the client, open manual posing and try dragging the slider back and forth, it can get stuck after just a bit (on Jomshir's browser).

**Comment by Jomshir98** [comment]
Using `useUpdatedUserInput` might simplify solving this, but it might not be enough when combined with pose limits. End solution should allow:
- Dragging slider smoothly, even on high ping
- Jump to valid positions from invalid ones when dragging
- The slider should update by itself if other character or item changes pose of this character
