### ISSUE TITLE
Dragable rectangle cutter to create previews in editor

### ISSUE THREAD

**Issue by Sekkmer** [Project-Pandora-Game/pandora#279]
Add a new 'Create Preview' button.

Shows a visual rectangle on a plane in the preview tab (or the setup tab)

The rectangle can be resized with a reasonable minimum.

Regardless of the size of the rectangle, the exported image should have the same size that we define as the preview size 100x100 or 200x200

Optionally the button could apply alpha 0 to the body so only the worn item is visible on the image.

The background should be transparent.

There should be an easy way to center the rectangle for asymmetric assets

Optionally: allow setting the height and width ratio as well as colored backgrounds to export things besides the preview

**Comment by ClaudiaMia** [comment]
Implemented by https://github.com/Project-Pandora-Game/pandora/pull/459
