### ISSUE TITLE
Improve device menu usability

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#284]
When a user opens the room device context menu in the room view, they are able to put a character into a character slot of that device.
However, when a character is not able to use the character slot (e.g. due to some restraints), that character is simply not listed in the context menu of the device as a possible character target.
This could be quite confusing to the user and also does not give them any help to find out the reason for that.

It is also inconsistent, as in the room inventory screen you get a hover message of why the character cannot use the device's character slot.

I propose to still also list characters that cannot use the slot, but highlight them in a way that it is clear that they are not eligible and also add the same hover-over explanation text.

**Comment by Jomshir98** [comment]
`WardrobeButton` can be used as example of how to make this change with hover.

Another useful improvement to this menu: Color character names by their colors to allow faster orientation in the menu.

**Comment by ClaudiaMia** [comment]
Implemented by https://github.com/Project-Pandora-Game/pandora/pull/465
