### ISSUE TITLE
Switching screens resets chat input mode

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#310]
Switching to the wardrobe (or other screens) reset the chosen chat input mode. It should stay persistent until you change it or leave the room.

**Comment by Jomshir98** [comment]
This should be solved by simple pulling `chatInputContext` higher up the virtual DOM tree (higher than `Router` so it keeps existing even while switching screens)

**Comment by ClaudiaMia** [comment]
I removed it from chatroom.tsx and moved it to index.tsx:

```
<React.StrictMode>
			<Dialogs />
			<HoverElementsPortal />
			<EulaGate>
				<ChatInputContextProvider>
					<BrowserRouter>
						<GameContextProvider>
							<Header />
							<ToastContainer theme='dark' />
							<div className='main'>
								<PandoraRoutes />
							</div>
						</GameContextProvider>
					</BrowserRouter>
				</ChatInputContextProvider>
			</EulaGate>
		</React.StrictMode>,
```

But this gives an error: Attempt to access ChatRoom outside of context

So it seems it is not as simple as you said.

**Comment by Jomshir98** [comment]
It seems I wasn't concrete enough where to move it - It is enough to move it outside of `PandoraRoutes` context, but the input provider itself depends on some other contexts inside `GameContextProvider`, so it needs to be lower than that. Looking closer at it better position might be placing it _inside_ `GameContextProvider`, right above `MiscProviders`.

**Comment by ClaudiaMia** [comment]
I tried your suggestion and also some other positions in that file's tree:
```
		<DebugContextProvider>
			<RootErrorBoundary>
				<NotificationContextProvider>
					<DirectoryConnectorContextProvider>
						<ShardConnectorContextProvider>
							<ChatInputContextProvider>
								<MiscProviders>
									{ children }
								</MiscProviders>
							</ChatInputContextProvider>
						</ShardConnectorContextProvider>
					</DirectoryConnectorContextProvider>
				</NotificationContextProvider>
			</RootErrorBoundary>
		</DebugContextProvider>
```

Outside `DebugContextProvider` I get a blank page and above as well as inside `MiscProviders`, I again get the error:
Attempt to access ChatRoom outside of context
