### ISSUE TITLE
Lint rule for flagging usage of deprecated functions/properties

### ISSUE THREAD

**Issue by Jomshir98** [Project-Pandora-Game/pandora#377]
Currently no point of our build tooling detects usage of deprecated functions/properties (anything having a `@deprecated` tag in comment).
We should either configure one of our existing tools (TypeScript or ESLint) to display error on deprecated usage detection (if there is such feature), or find a new ESLint plugin to do this.

**Comment by EveFerox** [comment]
done with [#519](https://github.com/Project-Pandora-Game/pandora/pull/519)

**Comment by EveFerox** [comment]
done with [#519](https://github.com/Project-Pandora-Game/pandora/pull/519)
