### ISSUE TITLE
Streamlining room construction

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#489]
I propose the following steps to improve the room construction experience:

- The way of entering the "room construction mode" no longer requires equipping "room construction tools"
- Instead, you enter the "room construction mode" via a new button in the room tab, next to the administration button.
- The button is only active and can be pressed if all prerequisites are fulfilled: 
  - Having permission, for instance by being admin
  - Same as before: Being able to use your hands to add/remove items (this point may not be logical now, so it needs a good toast message)
- The visual feedback is still there even without the tools:
  - Other players will see action messages about things in the room changing
  - The player in "room construction mode" will see a lot of red little buttons all over the canvas that are annoying and may lead to them leaving build mode when not needed. There is also no way to hide those, so this visual feedback is enough.
- "room construction mode" is left when:
  - The player presses the button in the room tab again
  - The player loses the ability to use their hands
  - The player loses the permission (e.g. by being demoted)
  - Note: I do not think a message about this happening is required, as you get clear visual feedback by the little red buttons disappearing all over the canvas in most cases. It will therefore be very obvious over time and other toast messages give enough guidance to new players, why something is not possible.
  
If someone wants to roleplay the act of constructing the room more visually, they can still equip the room construction tools as a normal handheld item without any special properties. But this will not fit to all roleplay scenarios and could be immersion breaking in some. Therefore, giving a choice instead of enforcing the usage of the tools is the best solution.

**Comment by ClaudiaMia** [comment]
I propose to add this to the beta 1 milestone, as I personally do not think the current room construction experience is the one we want to show to a wider user base. It would give a bad first impression.

**Comment by Sekkmer** [comment]
The "room construction mode" should be left on logout too

also, an idea: only check for room construction mode in all locations, and allow the enter action to be targeted, and only check if the source is an admin that way admins can allow others to change the room if they want
