### ISSUE TITLE
Improve behavior when account is both admin and banned in a room

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#492]
Currently, a room admin can be (maybe accidentally) be added to the ban list.

This has no effect in my tests, as the admin role seems to win.

I am not sure this is good behavior, as it is a bit hidden. I believe the behavior should maybe be changed so that:

- when you try to add an account as admin which is banned, open a popup to ask if it should be added as admin and removed from the ban list.
- when you try to ban an account that is admin, open a popup and ask if it should be banned and removed from the admin list.

**Comment by Sekkmer** [comment]
I feel admins should not be bannable, client should warn if the list is edited in a way it shouldn't be possible and server should drop admins from the list on change

Client should just say that admins must be demoted before ban, the only other hole I could see is development feature where some accounts can not be demoted, client should warn on demote in this case
