### ISSUE TITLE
do not share account username with other users, use display name instead

### ISSUE THREAD

**Issue by Sekkmer** [Project-Pandora-Game/pandora#505]
Relationships store a copy of the username, this will need to be updated on the display name change

there should be a limit on how frequently the display name can be changed, maybe once every week/month

(code should be checked if all possible paths of username sharing is removed)

**Comment by ClaudiaMia** [comment]
There also needs to be a way to set the display name somewhere, likely under settings > account.

... and if it is not set (like after registration), it should use the account ID as a display name substitute, I guess.
