### ISSUE TITLE
Improve space joining conditions

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#571]
The idea was that the behavior would be changed to the following:

You are only able to join an unlisted public rooms (no admin online inside) and private rooms, if:
- you are owner, admin, or on allow list
- ~~it is password protected and you know the password~~ Password mechanic should be removed altogether, see below
- you have a specially crafted valid invite link by an owner or admin (the generic `.../space/join/safgwsuzagasjasdfsafsah` is from my point of view not a valid invite link to join unless the room is listed fully public with no restrictions and anyone can join anyway)
- someone who is currently inside sends you a direct invite via DM that is only valid while they are online inside the space or maybe even additionally expire after 15 mins or so.

**Comment by Jomshir98** [comment]
I would also like to clarify that the third and fourth points boil down to "You have a valid invite".
Next think would be what is a "valid" invite.

We are thinking that invites should be create-able by both admins, but also by normal users wanting to invite their friends. This leads to two types of invites:
- Space-bound invite
  - Can only be created by admins+
  - Specifies all aspects of its validity (if it has expiry date, if it is limited to some account/character, if it has limited count of uses)
  - Can be used no matter the state of the space (even if the space is completely empty and unloaded)
  - Is created using a special UI with all options editable - its purpose is to serve complex cases
- "Join me" invite
  - Can be created by anyone (but has restrictions, see below)
  - Is bound to a specific target _account_ (as it can be sent via DM)
  - Is bound to a specific source _account_ - requires any character of the creator to be still online and inside the space for it to work
  - Is single use
  - Is valid for 2 hours [tunable]
  - Details cannot be edited by the one creating it - its purpose is to be simple, quick invite, meant for majority of cases
  
Now the question is what protections should each type of invite be able to bypass.
I think the first invite type should be able to bypass literally anything except space character limit - it can only be created by admins and admins could just modify the settings to let the new person in; so it is just a convenience feature.

The second type of invite can be created by anyone however, so it should be more restrictive, I propose the following:
  - If the author of the "join me" invite is an admin the invite just works (should this bypass size limit too?)
  - If the target can join the space without the help of the invite it works (e.g. they are vip+, or the room is normal public, visible room). This bypasses the following checks:
    - If the room is public, but no admin inside (so unlisted) the invite works anyway (to allow friends to still join you in public rooms that recently went silent)
    
Finally I think password mechanism should be removed altogether:
- It is redundant - all its uses can be fully modeled using "Space-bound" invite which is more flexible
- Complicates things - Behaves very differently based on if the room is public or not and adds another variable to all the logic
- Feels weird to see a public space, but then see it needs a password (why is it public then in the first place)
