### ISSUE TITLE
Add optional binding between room device modules and slots for permission check

### ISSUE THREAD

**Issue by Sekkmer** [Project-Pandora-Game/pandora#592]
Allow binding a room device module to a single slot optionally
When a module is bound to a slot and the slot is occupied changing the module should check for permissions on the character who occupies the slot

Same for lock modules: Those should respect the most restrictive value of any occupied slots' character permissions, in case the lock slot is ambiguous and not tied to a specific character slot.

So if a character has password locks blocked by permission then this lock slot module that is linked to the character slot should not allow this lock.

Note: Exclusive locks may also be a bit special with room devices. I guess they should prevent any character inside character slots linked to the lock module from opening the lock.

**Comment by ClaudiaMia** [comment]
There may be a dependency with this issue:
https://github.com/Project-Pandora-Game/pandora/issues/678

Right now, I believe every room device does not bind directly on entering a slot (exception may be what angela added for the bondage frame that has two slots to tie someone directly to the poles), which makes us able to either drop or change the current permission to enter/leave a room device, and then we need a permission that gates whether anyone can do any interaction (adding a lock, or using a module) that would trap someone in a room device.

That way we can allow others to put someone else on a sofa without needing to give them permission to trap you in a device.
