### ISSUE TITLE
Add a warning property to permissions

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#607]
Some permissions, such as allowing others to enter you in a device can get you stuck and new players may not be aware of this.

We wanted to:
- Add a new optional property to permissions for the warning message
- Modify the ask for permission dialog to show these warnings when the according permission is requested
- Show the warning maybe also in the permission settings UI somewhere
- Make use of this warning for the "enter or leave a device" permission

**Comment by Sekkmer** [comment]
this feels like duplication of #591

**Comment by Sekkmer** [comment]
edit the other issue, closing this one
