### ISSUE TITLE
Standardize Color Input Style

### ISSUE THREAD

**Issue by Madmanmayson** [Project-Pandora-Game/pandora#669]
Right now the color picker for choosing your account and character name colors use the default HTML <input type="color"> tag for handling color selection, causing it to use whatever your browser has built in whereas editing the color for an asset in the wardrobe brings up a specially designed component instead. 

I feel as though these should be standardized, likely by turning the wardrobe color input into a generic input component if it's not already, so it can be used globally, thereby allowing it to also be used for setting the character/account name colors as well as any other spots where it might be needed in the future.

**Comment by Jomshir98** [comment]
Good point!
The color picker already is a generic component (`ColorInput`), so it should be fairly easy to just replace the setting's color picker with the custom one.

**Comment by Madmanmayson** [comment]
Oh I didn't notice it under common directory since I was looking under the input directory instead. That will make it much easier to change!

**Comment by Madmanmayson** [comment]
Looking into this more, the name color changes are using the `ColorInput` component which in it's initial conception is set to utilize the HTML `<input type="color">` tag whereas the wardrobe uses the newer `ColorInputRGBA` component with it's custom design. 

The question becomes, should `ColorInput` be modified to create it's own `ColorEditor` component without an alpha channel being available as an option (passing in `minAlpha = Color.maxAlpha` as the parameter there), or should the setting options be switched over to the newer `ColorInputRGBA` component.
