### ISSUE TITLE
Make item randomization in room items work better

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#677]
when you're in a room item like a chair and you use the character randomization feature, it causes a desynchonisation where the chair gets removed from your body, but the chair still thinks you're sitting on it

**Comment by Jomshir98** [comment]
I think the correct fix here is to block the randomization from happening altogether when in a room device (similar to how it is blocked when you have an item on yourself that you can't remove).
The randomization is designed to have a full control over the full character's state in the end and if that isn't true it is not able to function properly, so blocking it while in a device feels sensible to me.
