### ISSUE TITLE
Improve interaction with room devices while unable to use hands

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#678]
It is quite unrealistic that you cannot enter/leave certain slots of room devices (e.g. sitting on something) while you have your hands tied.

~~Maybe we should add an attribute to slots that defines if you can enter/leave it while tied.~~

We just allow everyone with blocked hands to enter and leave slots that are not blocked from leaving by the asset.

**Comment by Sekkmer** [comment]
shouldn't the property be reversed and block enter leave if hands are tied
with the current devices I feel it make more sense that you can get into all of them when your hands are tied
pose requirements will prevent entering anyway you are tied

**Comment by ClaudiaMia** [comment]
> shouldn't the property be reversed and block enter leave if hands are tied with the current devices I feel it make more sense that you can get into all of them when your hands are tied pose requirements will prevent entering anyway you are tied

Sure, that makes sense to me.

**Comment by ClaudiaMia** [comment]
There may be a dependency with this issue:
https://github.com/Project-Pandora-Game/pandora/issues/592

Right now, I believe every room device does not bind directly on entering a slot (exception may be what angela added for the bondage frame that has two slots to tie someone directly to the poles), which makes us able to either drop or change the current permission to enter/leave a room device, and then we need a permission that gates whether anyone can do any interaction (adding a lock, or using a module) that would trap someone in a room device.

That way we can allow others to put someone else on a sofa without needing to give them permission to trap you in a device.

**Comment by ClaudiaMia** [comment]
Bumping it to high as it is a very common thing people stumble over. They find it illogical and it prevents them from roleplaying the way they want.

**Comment by ClaudiaMia** [comment]
Discussed this with Jomshir and we agreed that this issue will get a scope change and become very simple:
We just allow everyone with blocked hands to enter and leave slots that are not blocked from enter/leaving by the asset.
