### ISSUE TITLE
Add admin sub menu button to the room member list

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#686]
In the room tab, every other characters listed have a wardrobe and profile button currently.

The idea suggested by Elicia is that admins would see a 3rd button that is likely just a menu icon.
It would open an overlay telling for which character and account this sub menu is and then allow you to do certain admin actions, such as:

- kick
- ban
- add to allow list
- add to admin list

This way is quicker than trying to find and catch a potentially small, hidden, or moving textual link below a character or going into the according screen and tab to enter an id manually into a text field.

**Comment by SandrinePDR** [comment]
I'll have a go at this one
