### ISSUE TITLE
Custom pose save slots

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#687]
Give an account the ability to have a few custom pose save slots that add new custom pose buttons at the top of the view under the pose tab.

These buttons would function like normal pose buttons but need some sort of UI somewhere (tbd) that allows you to save the current pose slider and state values as they are all-in-one into one of those (server hosted) save slots. 

Optionally, the pose could be named, too, by the user.

**Comment by Jomshir98** [comment]
It would be great to have an ability for export/import for those that find the allocated storage unsatisfactory for them.
