### ISSUE TITLE
Improve long character slot selection lists

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#689]
In specific room item placements, and depending on the canvas size and resolution, as well as portrait/landscape, the selection menu cannot fit the screen and will be cut off, meaning part of the list will not be usable. It is not draggable or scrollable.

![image](https://github.com/Project-Pandora-Game/pandora/assets/99583892/1d5ecdaf-a3c7-468b-9e7b-4754e9041649)

**Comment by Jomshir98** [comment]
This has already been fixed in the above-mentioned PR.
