### ISSUE TITLE
Error when trying to send a direct message

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#703]
After logging in and trying to send a DM, sometimes the following error appears as a toast:
"Failed to send message: TypeError: Cannot read properties of undefined (reading 'encrypt')"

Source: https://discord.com/channels/872284471611760720/872568378190086174/1229169319594950776

**Comment by ClaudiaMia** [comment]
@Sekkmer 

I got the hint that this might be of interest to you~

**Comment by lina-cat** [comment]
I think i can reliably reproduce that, on my systems. My laptop doesn't seem to have the problem but my pc always does. If anyone can be helpful with giving me pointers i may try to debug

**Comment by ClaudiaMia** [comment]
Sekkmer might be the best one to ask since Sekkmer worked on this feature.

**Comment by lina-cat** [comment]
As a likely related issue: I noticed that at this point the message history is also not loaded at all. i.e. I see no active chats at all.

**Comment by Jomshir98** [comment]
Fixed by #792
