### ISSUE TITLE
Show the password / combination value to the one who entered it for safety and convenience

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#717]
Within https://github.com/Project-Pandora-Game/pandora/issues/491 we plan to store information about the one who created an item and on the one who last changed something about an item.

Potentially, there could be a custom property that stores who entered the value and then allows to do the following:
Showing the one who set a password / combination the value. 
Note: In the following I will only say password when I mean both.

This could be easy as we store the id of who locked a password. It just becomes tricky since we allow to lock a password with the previous set value, and showing it to the one locking it that way would leak the password.

This is fine for a combination lock where it is a bit silly that you cannot know the previous value (unless it is a digital lock where such a value could be secret), but for a password lock it could definitely be realistic to not know it.

So either 
1. we store the value of who inputted a password as a special data for just this kind of lock modules.
2. ~~we show the password also to the one who reused the last set value~~
3. ~~we remove the feature that you can lock a password again with the previous entered value~~

**Comment by Sekkmer** [comment]
I would remove option 3 as I would like the feature to remain, either the creator or the one who set the password last should be able to see it, or maybe offer both as a checkbox for the creator of the lock

**Comment by Sekkmer** [comment]
Ref: #751
